blank_issues_enabled: false
contact_links:
  - name: Pregunta general
    url: https://github.com/asdrubalivan/remote-venezuela-hiring/discussions
    about: Para preguntas generales abre una Discusión en lugar de un issue.
